workflows:
  android-apk-free:
    name: Android APK Build & GitHub Release
    environment:
      groups:
        - keystore
        - telegram_credentials
        - github_credentials  # Add this group for GitHub token
      vars:
        BUNDLE: "false"
    triggering:
      events:
        - pull_request
        - tag
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Create env file
        script: |
          cat > telegram.env << EOL
          BOT_TOKEN=$TELEGRAM_BOT_TOKEN
          CHAT_ID=$TELEGRAM_CHAT_ID
          GITHUB_TOKEN=$GITHUB_TOKEN
          EOL

      - name: Setup and Get Dependencies
        script: |
          flutter packages pub get

      - name: Run All Tests
        script: |
          echo "🧪 Running all tests..."
          flutter test --test-randomize-ordering-seed random
          echo "✅ All tests passed!"

      - name: Extract Version Info and Build APK
        script: |
          echo "📋 Extracting version information..."
          # Extract versionName and versionCode from pubspec.yaml
          VERSION_NAME=$(grep 'version:' pubspec.yaml | awk '{print $2}' | cut -d'+' -f1)
          VERSION_CODE=$(grep 'version:' pubspec.yaml | awk '{print $2}' | cut -d'+' -f2)
          
          echo "📦 Version Name: $VERSION_NAME"
          echo "🔢 Version Code: $VERSION_CODE"
          
          # Set custom APK name with hyphens
          CUSTOM_APK_NAME="mahakka-com-${VERSION_NAME}-${VERSION_CODE}.apk"
          echo "🏷️ Custom APK Name: $CUSTOM_APK_NAME"
          
          echo "🔍 Debug: Environment variables check..."
          echo "CM_KEYSTORE_BASE64: ${CM_KEYSTORE_BASE64:+(set)} (length: ${#CM_KEYSTORE_BASE64})"
          echo "CM_KEYSTORE_PASSWORD: ${CM_KEYSTORE_PASSWORD:+(set)} (length: ${#CM_KEYSTORE_PASSWORD})"
          echo "CM_KEY_ALIAS: ${CM_KEY_ALIAS:+(set)} (value: $CM_KEY_ALIAS)"
          echo "CM_KEY_PASSWORD: ${CM_KEY_PASSWORD:+(set)} (length: ${#CM_KEY_PASSWORD})"

          echo "🔐 Restoring keystore from base64..."
          echo -n "$CM_KEYSTORE_BASE64" | base64 -d > mahakka.keystore
          echo "✅ Keystore restored from base64"
          echo "🔐 Keystore file info: $(ls -la mahakka.keystore)"

          echo "🔐 Configuring signing for release build..."
          export STORE_FILE="mahakka.keystore"
          export STORE_PASSWORD="$CM_KEYSTORE_PASSWORD"
          export KEY_ALIAS="$CM_KEY_ALIAS"
          export KEY_PASSWORD="$CM_KEY_PASSWORD"

          echo "📋 Exporting signing environment variables:"
          echo "STORE_FILE: $STORE_FILE"
          echo "STORE_PASSWORD: ${STORE_PASSWORD:+(set)} (length: ${#STORE_PASSWORD})"
          echo "KEY_ALIAS: $KEY_ALIAS"
          echo "KEY_PASSWORD: ${KEY_PASSWORD:+(set)} (length: ${#KEY_PASSWORD})"

          echo "🏗️ Building APK..."
          flutter build apk --release

          echo "🏷️ Renaming APK to: $CUSTOM_APK_NAME"
          
          # Define source and target paths clearly
          SOURCE_APK="build/app/outputs/flutter-apk/app-release.apk"
          TARGET_APK="build/app/outputs/flutter-apk/$CUSTOM_APK_NAME"
          
          # Verify source APK exists before renaming
          if [ ! -f "$SOURCE_APK" ]; then
            echo "❌ Source APK not found: $SOURCE_APK"
            echo "📁 Directory contents:"
            ls -la build/app/outputs/flutter-apk/
            exit 1
          fi
          
          # Rename the built APK
          mv "$SOURCE_APK" "$TARGET_APK"
          
          echo "✅ APK renamed successfully"
          echo "📦 Final APK location: $TARGET_APK"
          echo "📊 File size: $(du -h "$TARGET_APK" | cut -f1)"
          
          # Verify the renamed file exists
          if [ -f "$TARGET_APK" ]; then
            echo "✅ Renamed APK verified and ready for publishing"
            # Write the custom APK name to a file for use in subsequent steps
            echo "$CUSTOM_APK_NAME" > custom_apk_name.txt
            # Also store version info for GitHub release
            echo "$VERSION_NAME" > version_name.txt
            echo "$VERSION_CODE" > version_code.txt
          else
            echo "❌ Renamed APK not found at expected location"
            exit 1
          fi

      - name: Verify Signing
        script: |
          echo "🔍 Verifying signature of renamed APK..."
          # Read the custom APK name from file
          CUSTOM_APK_NAME=$(cat custom_apk_name.txt)
          TARGET_APK="build/app/outputs/flutter-apk/$CUSTOM_APK_NAME"
          
          if [ ! -f "$TARGET_APK" ]; then
            echo "❌ APK not found for verification: $TARGET_APK"
            exit 1
          fi
          
          if keytool -printcert -jarfile "$TARGET_APK" 2>/dev/null; then
            echo "✅ APK is properly signed"
          else
            echo "❌ APK signing verification failed"
            exit 1
          fi

      - name: Extract and Display Signing Information
        script: |
          echo "=== APK SIGNING CERTIFICATE INFORMATION ==="
          echo "This information can be used to verify the APK authenticity"
          echo ""
          
          # Read the custom APK name from file
          CUSTOM_APK_NAME=$(cat custom_apk_name.txt)
          TARGET_APK="build/app/outputs/flutter-apk/$CUSTOM_APK_NAME"
          
          if [ -f "$TARGET_APK" ] && [ -n "$CM_KEYSTORE_PASSWORD" ]; then
            keytool -printcert -jarfile "$TARGET_APK"
          
            keytool -printcert -jarfile "$TARGET_APK" > signature_info.txt
          
            if command -v apksigner &> /dev/null; then
              echo ""
              echo "=== APKSIGNER VERIFICATION ==="
              apksigner verify --print-certs "$TARGET_APK"
            fi
          
            SHA256_FINGERPRINT=$(keytool -printcert -jarfile "$TARGET_APK" | grep "SHA256" | head -1 | sed 's/.*SHA256: //' | tr -d ':' | tr -d ' ')
            echo ""
            echo "=== QUICK VERIFICATION ==="
            echo "SHA-256 Fingerprint: $SHA256_FINGERPRINT"
          else
            echo "⚠️ No signing information available (unsigned build)"
            echo "This is a debug/unsigned APK for testing purposes"
          fi

      - name: Publish to GitHub Release
        script: |
          # Only publish on tag events or manual builds, not on pull requests
          if [ "$CM_PULL_REQUEST" = "true" ]; then
            echo "📝 Pull request build - skipping GitHub release"
            exit 0
          fi

          echo "🚀 Preparing GitHub Release..."
          
          # Read version info
          CUSTOM_APK_NAME=$(cat custom_apk_name.txt)
          VERSION_NAME=$(cat version_name.txt)
          VERSION_CODE=$(cat version_code.txt)
          
          # Set up GitHub CLI authentication
          if [ -z "$GITHUB_TOKEN" ]; then
            echo "❌ GITHUB_TOKEN not set. Please add it to github_credentials group."
            exit 1
          fi
          
          echo "$GITHUB_TOKEN" > token.txt
          gh auth login --with-token < token.txt
          rm token.txt
          
          # Verify authentication
          gh auth status
          
          # Get repository info
          REPO_OWNER=$(echo $CM_REPO_SLUG | cut -d'/' -f1)
          REPO_NAME=$(echo $CM_REPO_SLUG | cut -d'/' -f2)
          
          echo "📦 Repository: $CM_REPO_SLUG"
          echo "🏷️ Release tag: $CUSTOM_APK_NAME"
          
          # Create GitHub release
          RELEASE_NOTES="Mahakka App Release
          Version: $VERSION_NAME
          Build: $VERSION_CODE
          Built on: $(date)
          SHA-256: $(keytool -printcert -jarfile "build/app/outputs/flutter-apk/$CUSTOM_APK_NAME" 2>/dev/null | grep "SHA256" | head -1 | sed 's/.*SHA256: //' | tr -d ':' | tr -d ' ' || echo "Unknown")"
          
          echo "📝 Creating GitHub release..."
          gh release create "$CUSTOM_APK_NAME" \
            "build/app/outputs/flutter-apk/$CUSTOM_APK_NAME" \
            --title "Mahakka $VERSION_NAME ($VERSION_CODE)" \
            --notes "$RELEASE_NOTES" \
            --repo "$CM_REPO_SLUG"
          
          echo "✅ GitHub release created successfully!"
          echo "🔗 Release URL: https://github.com/$CM_REPO_SLUG/releases/tag/$CUSTOM_APK_NAME"

    artifacts:
      - build/app/outputs/flutter-apk/mahakka-com-*.apk
      - custom_apk_name.txt
      - version_name.txt
      - version_code.txt
      - signature_info.txt

    publishing:
      email:
        recipients:
          - bitcoinizado@proton.me
        notify:
          success: true
          failure: true