workflows:
  android-apk-free:
    name: Android APK Build & GitHub Release
    environment:
      groups:
        - keystore
      vars:
        BUNDLE: "false"
        #GH_REPO: ""  # Optional: override target repository
    scripts:
      - name: Setup and Build
        script: |
          flutter packages pub get
          
          # Set signing environment variables for Gradle
          if [ -f "android/app/mahakka.keystore" ] && [ -n "$CM_KEYSTORE_PASSWORD" ]; then
          echo "🔐 Configuring signing for release build..."
          export STORE_FILE="mahakka.keystore"
          export STORE_PASSWORD="$CM_KEYSTORE_PASSWORD"
          export KEY_ALIAS="mahakka"
          export KEY_PASSWORD="${CM_KEY_PASSWORD:-$CM_KEYSTORE_PASSWORD}"
          else
          echo "⚠️ Building unsigned APK (no keystore or password)"
          # Clear any previous signing environment variables
          unset STORE_FILE
          unset STORE_PASSWORD
          unset KEY_ALIAS
          unset KEY_PASSWORD
          fi
          
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/*.apk

    publishing:
      email:
        recipients:
          - bitcoinizado@proton.me
        notify:
          success: true
          failure: true