name: mahakka
description: An app using the memo protocol to publish content to the BCH blockchain.
publish_to: 'none'
version: 1.1.1-BCH+20250904

environment:
  sdk: '3.9.2'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  badges: ^3.1.2
  flutter_native_splash: ^2.4.6
  flutter_confetti: ^0.5.1
  cupertino_icons: ^1.0.8
  pretty_qr_code: ^3.5.0
  bip39_mnemonic: ^4.0.1
  clipboard: ^2.0.2
  html: ^0.15.6
  shared_preferences: ^2.5.3
  youtube_player_flutter: ^9.1.2
  fluttertagger: ^2.3.1
  linkify: ^5.0.0
  url_launcher: ^6.3.2
  http: ^1.5.0
  provider: ^6.1.5+1
  uuid: ^4.5.1
  intl: ^0.20.2
  expandable_text: ^2.3.0
  zoom_pinch_overlay: ^1.4.3
  flutter_staggered_grid_view: ^0.7.0
  path_provider: ^2.1.5
  bitcoin_base: ^6.8.0
  blockchain_utils: ^5.2.0
  background_json_parser: ^1.0.7
  json5: ^0.8.2
  json_path: ^0.7.6
  path: ^1.9.1
  json_annotation: ^4.9.0
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  isar_community: ^3.3.0-dev.1  # Correct package name
  isar_community_flutter_libs: ^3.3.0-dev.1  # Correct package name

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  flutter_lints: ^6.0.0
  isar_community_generator: ^3.3.0-dev.1  # Correct package name

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - shorebird.yaml

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android: true
  web: true